# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
import random
arr = np.random.uniform(0, 20, 28).reshape(4,7)
print("Матрица: \n", arr)
norm_vid = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("Норм матрица: \n", norm_vid)


Матрица: 
 [[14.65832816 14.29725534 11.18417842 18.60351637 12.74360736 14.76213099
   2.88794803]
 [ 6.97369296  7.37809697  8.21371966 10.89474552 18.82172912  6.23998186
  17.13637636]
 [11.15649377 14.47670065  2.9533678   7.21621241  9.06900447  3.87031571
  12.8304267 ]
 [16.26473671  6.96229153  8.52664443  7.83601606  8.79422903 14.52056945
  17.65790454]]
Норм матрица: 
 [[0.73870603 0.71604519 0.52066928 0.98630502 0.61853864 0.74522067
  0.        ]
 [0.2564203  0.28180059 0.33424406 0.50250455 1.         0.21037278
  0.89422769]
 [0.5189318  0.72730713 0.00410573 0.27164076 0.38792151 0.06165314
  0.6239874 ]
 [0.83952381 0.25570475 0.35388313 0.31053948 0.37067668 0.73006033
  0.92695867]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.randint(0, 10, size = (8, 10))
print("Матрица: \n", arr)
min_str = min((r for r in arr), key = sum)
print("Строка с наименьшей суммой чисел: \n", min_str)





Матрица: 
 [[6 0 4 3 5 0 9 0 0 6]
 [4 4 0 7 7 8 7 2 6 7]
 [5 0 6 9 0 2 8 3 3 8]
 [0 2 9 1 6 3 0 8 3 8]
 [8 9 1 5 7 2 4 5 9 7]
 [2 7 5 3 2 5 8 3 2 8]
 [6 9 6 6 1 0 3 3 5 3]
 [8 2 7 2 8 8 4 5 2 3]]
Строка с наименьшей суммой чисел: 
 [6 0 4 3 5 0 9 0 0 6]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [11]:
a = np.array((0, 0, 0))
b = np.array((3, 3, 3))
dis = np.linalg.norm(a-b)
print(dis)


5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [20]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
Ai = np.linalg.inv(A)
Bi = np.linalg.inv(B)
C1 = C*(-1)
res1 = np.dot(C1, Bi)
res2 = np.dot(Ai, res1)
print(np.around(res2))

[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [4]:
import numpy as np
stroki = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)
print(stroki[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
print("Среднее значение: ", np.mean(stroki[:, 1:], 0))
print("Максимальное значение: ", np.max(stroki[:, 1:], 0))
print("Минимальное значение: ", np.min(stroki[:, 1:], 0))
print("Медиана: ", np.median(stroki[:, 1:], 0))

Среднее значение:  [2.16010017e+04 9.05528000e+00]
Максимальное значение:  [2147483647         39]
Минимальное значение:  [0 1]
Медиана:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
tm = np.quantile(stroki[:,1], 0.75)
print(tm)


65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
un = np.unique(stroki[:, 0])
print(len(un))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.